apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: inventory-service
data:
  # Database connection information
  PG_HOST: "terraform-20250721141508797700000004.cmw3e40chj7r.us-east-1.rds.amazonaws.com"
  PG_CONTAINER: "postgres-inventorydb"
  DATASOURCE_PORT: "5432"
  ENVIRONMENT: "production"
  PG_DB: "inventorydb"
  PG_USER: "inventoryuser"
  PG_PASS: "password123"
  PG_PORT: "5432"

  # Spring Boot specific configuration
  SPRING_PROFILES_ACTIVE: "production"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://terraform-20250721141508797700000004.cmw3e40chj7r.us-east-1.rds.amazonaws.com:5432/inventorydb"
  SPRING_DATASOURCE_USERNAME: "inventoryuser"
  SPRING_DATASOURCE_PASSWORD: "password123"

  # Standard JDBC URL for other frameworks
  DATASOURCE_URL: "jdbc:postgresql://terraform-20250721141508797700000004.cmw3e40chj7r.us-east-1.rds.amazonaws.com:5432/inventorydb"

  # Flag to indicate environment
  DEPLOYMENT_ENV: "cloud"
