apiVersion: v1
kind: Pod
metadata:
  name: postgres-test
  namespace: order-service
spec:
  containers:
    - name: postgres-client
      image: postgres:14-alpine
      command: ["sleep", "3600"]
      env:
        - name: PGHOST
          value: "terraform-20250721141508796600000003.cmw3e40chj7r.us-east-1.rds.amazonaws.com"
        - name: PGPORT
          value: "5432"
        - name: PGDATABASE
          value: "orderdb"
        - name: PGUSER
          value: "orderuser"
        - name: PGPASSWORD
          value: "orderpass"
