apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: order-system-kubernetes
build:
  artifacts:
    - image: 294417223953.dkr.ecr.us-east-1.amazonaws.com/inventory-service
      context: apps/inventory-service
      docker:
        dockerfile: Dockerfile
    - image: 294417223953.dkr.ecr.us-east-1.amazonaws.com/order-service
      context: apps/order-service
      docker:
        dockerfile: Dockerfile
    - image: 294417223953.dkr.ecr.us-east-1.amazonaws.com/payment-service
      context: apps/payment-service
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: order-service
        chartPath: helm/order-service
        valuesFiles:
          - helm/order-service/values.yaml
        setValues:
          env.DATASOURCE_URL: "jdbc:postgresql://order-service-pg:5432/orderdb"
          env.DATASOURCE_PORT: "5432"
          env.ENVIRONMENT: "localhost"
        version: 0.1.0
      # - name: inventory-service
      #   chartPath: helm/inventory-service
      #   valuesFiles:
      #     - helm/inventory-service/values.yaml
      #   setValues:
      #     env.DATASOURCE_URL: "jdbc:postgresql://inventory-service-pg:5432/inventorydb"
      #     env.DATASOURCE_PORT: "5432"
      #     env.ENVIRONMENT: "localhost"
      #   version: 0.1.0
      - name: payment-service
        chartPath: helm/payment-service
        valuesFiles:
          - helm/payment-service/values.yaml
        setValues:
          env.DATASOURCE_URL: "jdbc:postgresql://payment-service-pg:5432/paymentdb"
          env.DATASOURCE_PORT: "5432"
          env.ENVIRONMENT: "localhost"
        version: 0.1.0
