FROM amazon/aws-cli:latest

# Install Terraform
RUN yum install -y yum-utils unzip curl && \
    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo && \
    yum -y install terraform && \
    yum clean all

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# Set AWS CLI to use the shared credentials
ENV AWS_SDK_LOAD_CONFIG=1