apiVersion: v1
kind: Service
metadata:
  name: order-service-external
  namespace: order-service
  labels:
    app: order-service
    part-of: order-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Use Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  externalTrafficPolicy: Cluster # This distributes traffic evenly across all nodes
