apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: payment-service
data:
  # Database connection information
  PG_HOST: "terraform-20250721141508796600000003.cmw3e40chj7r.us-east-1.rds.amazonaws.com"
  PG_CONTAINER: "postgres-paymentdb"
  DATASOURCE_PORT: "5432"
  ENVIRONMENT: "production"
  PG_DB: "paymentdb"
  PG_USER: "paymentuser"
  PG_PASS: "password123"
  PG_PORT: "5432"
  
  # Spring Boot specific configuration
  SPRING_PROFILES_ACTIVE: "production"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://terraform-20250721141508796600000003.cmw3e40chj7r.us-east-1.rds.amazonaws.com:5432/paymentdb"
  SPRING_DATASOURCE_USERNAME: "paymentuser"
  SPRING_DATASOURCE_PASSWORD: "password123"
  
  # Standard JDBC URL for other frameworks
  DATASOURCE_URL: "jdbc:postgresql://terraform-20250721141508796600000003.cmw3e40chj7r.us-east-1.rds.amazonaws.com:5432/paymentdb"
  
  # Flag to indicate environment
  DEPLOYMENT_ENV: "cloud"
