apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}  # Define the hostname here, like inventory-service.local
      http:
        paths:
          - path: /  # The absolute path here. It will match "/"
            pathType: Prefix  # Use 'Prefix' to match any path that starts with "/"
            backend:
              service:
                name: {{ .Release.Name }}  # The name of the service being routed to (e.g., inventory-service)
                port:
                  number: {{ .Values.service.port }}  # The port the service listens to (e.g., 8080)
