apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-paymentdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-payment
  template:
    metadata:
      labels:
        app: postgres-payment
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          env:
            - name: POSTGRES_DB
              value: "paymentdb"
            - name: POSTGRES_USER
              value: "paymentuser"
            - name: POSTGRES_PASSWORD
              value: "paymentpass"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql-payment/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-payment-pvc
