apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-order-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Increase from 128Mi to at least 1Gi